version: '3.7'
services:
  terraform:
    image: hashicorp/terraform:0.12.25
    container_name: terraform
    volumes:
      - ./:/workdir
      - ./.credentials/account.json:/workdir/.credentials/account.json
    working_dir: "/workdir"
  gcloud:
    image: google/cloud-sdk:292.0.0
    container_name: gcloud
    volumes:
      - ./:/workdir
      - ./.credentials/account.json:/workdir/.credentials/account.json
    working_dir: "/workdir"
